- name: Create a directory to hold the mirror of the external data.
  ansible.builtin.file:
    path: /external-data/MD5/
    state: directory
    mode: '0755'

- name: Check if machine has SSH access to the main data store.
  ansible.builtin.command: ssh {{ main_server_user }}@{{ main_server_ip }} 'echo success'
  register: connected

- name: Exchange SSH keys with linode so we can access the data.
  import_tasks: exchange-keys.yml
  when: connected.stdout != "success"

- name: Mirror the external data from the main server in a volume (this may take a while).
  ansible.builtin.command: "rsync -az --perms -o -g {{ main_server_ip }}:/srv/{{ main_server_ip }}/ftp/external-data/MD5/ /external-data/MD5/"

- name: Copy the data update script onto the mirror machine.
  ansible.builtin.copy:
    src: ./update-external-data.sh
    dest: /external-data/update-external-data.sh
    mode: '0755'

- name: Create a crontab job that runs periodically to keep the data up to date.
  ansible.builtin.cron:
    name: Update external data
    minute: "*/5"
    job: /external-data/update-external-data.sh {{ main_server_ip }} >> /external-data/update-log.txt 2>&1
